---
actions: &common_actions
  post-upstream-clone:
    #- bash -c "env"
    - bash -c "mv --no-clobber *.spec ${PACKIT_SPECFILE_PATH}"
    - bash -c "rpmautospec process-distgit ${PACKIT_SPECFILE_PATH} ${PACKIT_SPECFILE_PATH}"
  get-current-version:
    - bash -c "grep -oP '^%global\s+tag\s+v\K.*' ${PACKIT_SPECFILE_PATH}"
  create-archive:
    - bash -c "spectool --get-files ${PACKIT_SPECFILE_PATH}"
    - bash -c "sha256sum -c CHECKSUM"
    - bash -c "echo ${PACKIT_PROJECT_NAME_VERSION}.tar.gz"

upstream_tag_template: protonplus-{version}

packages:
  protonplus:
    upstream_package_name: ProtonPlus
    downstream_package_name: protonplus
    update_release: false
    actions:
      <<: *common_actions
      fix-spec-file:
        - "true"
  protonplus-next:
    upstream_package_name: ProtonPlus
    downstream_package_name: protonplus-next
    actions:
      <<: *common_actions
      post-modifications:
        - bash -c "sed -i '0,/protonplus/ s//protonplus-next/' ${PACKIT_SPECFILE_PATH}"
        - bash -c "sed -i 's/%{name}/protonplus/g' ${PACKIT_SPECFILE_PATH}"

srpm_build_deps:
  - rpmautospec

jobs:
  - &common_job
    job: copr_build
    owner: wehagy
    project: test
    list_on_homepage: true
    targets:
      - fedora-all
    trigger: release
    identifier: protonplus
    packages:
      - protonplus

  - <<: *common_job
    trigger: pull_request
    identifier: protonplus-next
    packages:
      - protonplus-next
    notifications:
      pull_request:
        successful_build: true
      failure_comment:
        message: |
          One of the tests failed for {commit_sha}:
          - Check logs {logs_url}.
          - Packit dashboard {packit_dashboard_url}.
          - Copr dashboard {external_dashboard_url}.
