---
actions: &common_actions
  post-upstream-clone:
    - bash -c "rpmautospec process-distgit ${PACKIT_SPECFILE_PATH} ${PACKIT_SPECFILE_PATH}"
  get-current-version:
    - bash -c "grep -oP '^%global\s+tag\s+v\K.*' ${PACKIT_SPECFILE_PATH}"
  create-archive:
    - bash -c "spectool --get-files ${PACKIT_SPECFILE_PATH}"
    - bash -c "sha256sum -c CHECKSUM"
    - bash -c "echo ${PACKIT_PROJECT_NAME_VERSION}.tar.gz"

upstream_tag_template: protonplus-{version}

packages:
  protonplus:
    upstream_package_name: ProtonPlus
    downstream_package_name: protonplus
    update_release: false
    actions:
      <<: *common_actions
      fix-spec-file:
        - "true"
  protonplus-stg:
    upstream_package_name: ProtonPlus
    downstream_package_name: protonplus
    update_release: false
    actions:
      <<: *common_actions
      fix-spec-file:
        - "true"
  protonplus-dev:
    upstream_package_name: ProtonPlus
    downstream_package_name: protonplus
    actions:
      <<: *common_actions

srpm_build_deps:
  - rpmautospec

jobs:
  - job: copr_build
    owner: wehagy
    project: test
    list_on_homepage: true
    targets:
      - fedora-all
    trigger: release
    identifier: protonplus
    packages:
      - protonplus

  - job: copr_build
    owner: wehagy
    project: test
    list_on_homepage: true
    targets:
      - fedora-all
    trigger: commit
    identifier: protonplus-stg
    packages:
      - protonplus-stg

  - job: copr_build
    targets:
      - fedora-all
    trigger: pull_request
    identifier: protonplus-dev
    packages:
      - protonplus-dev
    notifications:
      pull_request:
        successful_build: true
      failure_comment:
        message: |
          One of the tests failed for {commit_sha}:
          - Check logs {logs_url}.
          - Packit dashboard {packit_dashboard_url}.
          - Copr dashboard {external_dashboard_url}.
