---
actions: &common_actions
  post-upstream-clone:
    - bash -c "rpmautospec process-distgit {*,*}.spec"
  create-archive:
    - bash -c "spectool --get-files --force *.spec"
    - bash -c "sha256sum -c CHECKSUM"
    - bash -c "echo *.tar.gz"

packages:
  protonplus:
    downstream_package_name: protonplus
    update_release: false
  protonplus-next:
    downstream_package_name: protonplus-next
    #release_suffix: {original_release_number}.{current_time}.{sanitized_current_branch}{git_desc_suffix}
    actions:
      <<: *common_actions
      post-upstream-clone:
        - bash -c "rpmautospec process-distgit {*,*}.spec"
        - bash -c "mv protonplus.spec protonplus-next.spec"
      post-modifications:
        - bash -c "sed -i '0,/protonplus/ s//protonplus-next/' *.spec"
        - bash -c "sed -i 's/%{name}/protonplus/g' *.spec"

upstream_package_name: ProtonPlus

upstream_tag_template: protonplus-{version}-1

srpm_build_deps:
  - rpmautospec

jobs:
  - &common_job
    job: copr_build
    owner: wehagy
    project: test
    list_on_homepage: true
    targets:
      - fedora-all
    trigger: release
    identifier: protonplus
    packages:
      - protonplus

  - <<: *common_job
    trigger: pull_request
    identifier: protonplus-next
    packages:
      - protonplus-next
    notifications:
      pull_request:
        successful_build: true
      failure_comment:
        message: |
          One of the tests failed for {commit_sha}:
          - Check logs {logs_url}.
          - Packit dashboard {packit_dashboard_url}.
          - Copr dashboard {external_dashboard_url}.
