---
upstream_package_name: ProtonPlus
downstream_package_name: protonplus

actions:
  fix-spec-file:
    - sh -c "spectool --get-files --force *.spec"

jobs:
- job: copr_build
  trigger: pull_request
  owner: wehagy
  project: test
  targets:
    - fedora-stable
    - fedora-rawhide
