# Build source RPM and RPM
---
name: Build source RPM and RPM
on:
  # Allows manual workflow run (must in default branch to work)
  workflow_dispatch:
  push:
    branches:
      - main
      - 'protonplus-next/**'

env:
  DNF_CMD: >
    dnf install 
      --assumeyes 
      --nodocs 
      --setopt=install_weak_deps=False

jobs:
  build-packages:
    name: Build SRPM and RPM
    runs-on: ubuntu-24.04
    container: 
      image: fedora:latest
      volumes:
        # overlay is not supported over overlayfs
        - non_overlay_dir:/var/lib/containers
      # mock inside docker need this option
      options: --privileged

    steps:
      - name: Install dependencies
        run: |
          ${DNF_CMD} \
            git \
            make

      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          # fetch all history to make changelog
          fetch-depth: 0

      - name: Build the SRPM
        run: |
          make srpm
          mv output/srpm/build.{log,srpm.log.txt}

      - name: Upload SRPM build log
        uses: actions/upload-artifact@v7
        with:
          retention-days: 30
          archive: false
          path: |
            output/srpm/build.srpm.log.txt

      - name: Upload SRPM
        uses: actions/upload-artifact@v7
        with:
          name: srpm
          retention-days: 30
          path: |
            output/srpm

      - name: Build the RPM
        run: |
          make rpm
          mv output/rpm/build.{log,rpm.log.txt}

      - name: Upload RPM expanded specfile
        uses: actions/upload-artifact@v7
        with:
          retention-days: 30
          archive: false
          path: |
            output/rpm/expanded-spec.txt

      - name: Upload RPM build log
        uses: actions/upload-artifact@v7
        with:
          retention-days: 30
          archive: false
          path: |
            output/rpm/build.rpm.log.txt

      - name: Upload RPM
        uses: actions/upload-artifact@v7
        with:
          name: rpm
          retention-days: 30
          path: |
            output/rpm

      - name: Fedora review
        run: |
          make review

      - name: Upload license check
        uses: actions/upload-artifact@v7
        with:
          retention-days: 30
          archive: false
          path: |
            output/review/licensecheck.txt

      - name: Upload review file
        uses: actions/upload-artifact@v7
        with:
          retention-days: 30
          archive: false
          path: |
            output/review/review.txt

      - name: Upload rpmlint
        uses: actions/upload-artifact@v7
        with:
          retention-days: 30
          archive: false
          path: |
            output/review/rpmlint.txt

      - name: Upload full review
        uses: actions/upload-artifact@v7
        with:
          name: review
          retention-days: 30
          path: |
            output/review
