---
name: source RPM build for Fedora Copr
on:
  # Allows manual workflow run (must in default branch to work)
  workflow_dispatch:

jobs:
  build:
    name: Submit a build from Fedora container
    runs-on: ubuntu-24.04
    container: fedora:latest

    steps:
      - name: Check out proper version of sources
        uses: actions/checkout@v4

      - name: Install API token for copr-cli
        env:
          API_TOKEN_CONTENT: ${{ secrets.COPR_API_TOKEN }}
        run: |
          mkdir -p "${HOME}/.config"
          echo "${API_TOKEN_CONTENT}" > "${HOME}/.config/copr"

      - name: Install tooling for source RPM build
        run: |
          dnf install --nodocs -y \
            copr-cli \
            fedpkg \
            make \
            meson

      - name: Build the source RPM
        run: |
          spectool -g *.spec
          fedpkg --release rawhide srpm -- --define "_srcrpmdir srpm"

      - name: Submit the build by uploading the source RPM
        run: copr build protonplus srpm/*.src.rpm
